package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const marker = "generate:reset"

type targetStruct struct {
	Name   string
	Fields []*ast.Field
}

func main() {
	root := flag.String("root", ".", "project root directory")
	flag.Parse()

	if err := run(*root); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string) error {
	root, err := filepath.Abs(root)
	if err != nil {
		return err
	}

	pkgs := make(map[string][]*targetStruct)

	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "vendor" || name == "profiles" || name == ".tools" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		dir := filepath.Dir(path)

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}

		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if !hasMarker(gen.Doc) && !hasMarker(ts.Doc) {
					continue
				}
				pkgs[dir] = append(pkgs[dir], &targetStruct{
					Name:   ts.Name.Name,
					Fields: st.Fields.List,
				})
			}
		}

		return nil
	})
	if err != nil {
		return err
	}

	if len(pkgs) == 0 {
		return errors.New("no // generate:reset structs found")
	}

	for dir, structs := range pkgs {
		if err := writePackageResetFile(dir, structs); err != nil {
			return err
		}
	}

	return nil
}

func hasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		txt := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if txt == marker {
			return true
		}
	}
	return false
}

func writePackageResetFile(dir string, structs []*targetStruct) error {
	sort.Slice(structs, func(i, j int) bool { return structs[i].Name < structs[j].Name })

	pkgName, err := detectPackageName(dir)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/reset; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for _, st := range structs {
		generateResetMethod(&buf, st)
		buf.WriteByte('\n')
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format %s/reset.gen.go: %w\n\n%s", dir, err, buf.String())
	}

	outPath := filepath.Join(dir, "reset.gen.go")
	return os.WriteFile(outPath, src, 0o644)
}

func detectPackageName(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}

	fset := token.NewFileSet()
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || strings.HasSuffix(name, ".gen.go") {
			continue
		}
		path := filepath.Join(dir, name)
		f, err := parser.ParseFile(fset, path, nil, parser.PackageClauseOnly)
		if err != nil {
			continue
		}
		return f.Name.Name, nil
	}
	return "", fmt.Errorf("cannot detect package name in %s", dir)
}

func generateResetMethod(buf *bytes.Buffer, st *targetStruct) {
	fmt.Fprintf(buf, "func (x *%s) Reset() {\n", st.Name)
	fmt.Fprintf(buf, "\tif x == nil {\n\t\treturn\n\t}\n")

	for _, fld := range st.Fields {
		if len(fld.Names) == 0 {
			name, ok := embeddedFieldName(fld.Type)
			if !ok {
				continue
			}
			emitResetForType(buf, "x."+name, fld.Type)
			continue
		}

		for _, name := range fld.Names {
			emitResetForType(buf, "x."+name.Name, fld.Type)
		}
	}

	fmt.Fprintf(buf, "}\n")
}

func embeddedFieldName(t ast.Expr) (string, bool) {
	switch tt := t.(type) {
	case *ast.Ident:
		return tt.Name, true
	case *ast.SelectorExpr:
		return tt.Sel.Name, true
	case *ast.StarExpr:
		return embeddedFieldName(tt.X)
	default:
		return "", false
	}
}

func emitResetForType(buf *bytes.Buffer, sel string, t ast.Expr) {
	switch tt := t.(type) {
	case *ast.Ident:
		if z, ok := basicZeroValue(tt.Name); ok {
			fmt.Fprintf(buf, "\t%s = %s\n", sel, z)
			return
		}
		emitResettableOrZero(buf, sel, t)
	case *ast.ArrayType:
		if tt.Len == nil {
			fmt.Fprintf(buf, "\t%s = %s[:0]\n", sel, sel)
			return
		}
		emitZeroAssignment(buf, sel, t)
	case *ast.MapType:
		fmt.Fprintf(buf, "\tclear(%s)\n", sel)
	case *ast.StarExpr:
		fmt.Fprintf(buf, "\tif %s != nil {\n", sel)
		fmt.Fprintf(buf, "\t\tif r, ok := any(%s).(interface{ Reset() }); ok {\n", sel)
		fmt.Fprintf(buf, "\t\t\tr.Reset()\n")
		fmt.Fprintf(buf, "\t\t} else {\n")
		emitResetForType(buf, "(*"+sel+")", tt.X)
		fmt.Fprintf(buf, "\t\t}\n")
		fmt.Fprintf(buf, "\t}\n")
	case *ast.StructType:
		emitZeroAssignment(buf, sel, t)
	default:
		emitResettableOrZero(buf, sel, t)
	}
}

func emitResettableOrZero(buf *bytes.Buffer, sel string, t ast.Expr) {
	fmt.Fprintf(buf, "\tif r, ok := any(&%s).(interface{ Reset() }); ok {\n", sel)
	fmt.Fprintf(buf, "\t\tr.Reset()\n")
	fmt.Fprintf(buf, "\t} else {\n")
	emitZeroAssignment(buf, sel, t)
	fmt.Fprintf(buf, "\t}\n")
}

func emitZeroAssignment(buf *bytes.Buffer, sel string, t ast.Expr) {
	fmt.Fprintf(buf, "\t{\n")
	fmt.Fprintf(buf, "\t\tvar zero %s\n", exprString(t))
	fmt.Fprintf(buf, "\t\t%s = zero\n", sel)
	fmt.Fprintf(buf, "\t}\n")
}

func basicZeroValue(typeName string) (string, bool) {
	switch typeName {
	case "string":
		return `""`, true
	case "bool":
		return "false", true
	case "int", "int8", "int16", "int32", "int64":
		return "0", true
	case "uint", "uint8", "uint16", "uint32", "uint64", "uintptr":
		return "0", true
	case "float32", "float64":
		return "0", true
	case "complex64", "complex128":
		return "0", true
	default:
		return "", false
	}
}

func exprString(e ast.Expr) string {
	var b bytes.Buffer
	_ = format.Node(&b, token.NewFileSet(), e)
	return b.String()
}
